CREATE TABLE `STUDENT` (
	`id` SERIAL NOT NULL,
	`NO` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	`NAME` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
	`ENT_YEAR` INT(10),
	`CLASS_NUM` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
	`IS_ATTEND` BOOLEAN,
	`SCHOOL_CD` CHAR(3),
	PRIMARY KEY (`id`,`NO`)
) ENGINE=InnoDB;